services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  huh.events.event_listener.data_container.calendar_events_listener:
    class: HeimrichHannot\EventsBundle\EventListener\DataContainer\CalendarEventsListener
    public: true
    autowire: true

  huh.events.event_listener.data_container.calendar_sub_events_listener:
    class: HeimrichHannot\EventsBundle\EventListener\DataContainer\CalendarSubEventsListener
    public: true
    autowire: true

  huh.events.event_listener.data_container.content_listener:
    class: HeimrichHannot\EventsBundle\EventListener\DataContainer\ContentListener
    public: true
    autowire: true

  huh.events.event_listener.hook.hook_listener:
    class: HeimrichHannot\EventsBundle\EventListener\Hook\HookListener
    public: true
    autowire: true